// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kksdvmvrqvwrahtopbir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2R2bXZycXZ3cmFodG9wYmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjQxNDksImV4cCI6MjA2OTM0MDE0OX0.UjksCUbdvqbVPCS9gJasoyOEN_msHlwW1tG0AV2W8qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});